/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   prism-highlighter.html
 */

/// <reference path="prism-import.d.ts" />
/// <reference path="prism-highlighter-src.d.ts" />

